### ISSUE TITLE
plz add data format supportting, thx

### ISSUE THREAD

**Issue by heartacker** [attilathedud/vscode-data-converter#1]
hi this ext is very usful, and it will be better for add format support，
for example:
I want to convert dec-hex;
10-->0xA
350--0x15E
I want this ext can provide the option that we can specify the "Length", like:
10--->0x00A
350-->0X15E
so that I can  align my code easier. thx

**Comment by attilathedud** [comment]
Sure, I can add it in as a configuration option. Do you want absolute length or padding? I've shown an example of the two below:

Length of 2 would always add 2 zeros:
10--->0x00A
350-->0X0015E

Padding of 3 would pad every number out to 3 digits:
10--->0x00A
350-->0X15E

I'm assuming you want padding but I just want to make sure.

**Comment by heartacker** [comment]
> Sure, I can add it in as a configuration option. Do you want absolute length or padding? I've shown an example of the two below:
> 
> Length of 2 would always add 2 zeros:
> 10--->0x00A
> 350-->0X0015E
> 
> Padding of 3 would pad every number out to 3 digits:
> 10--->0x00A
> 350-->0X15E
> 
> I'm assuming you want padding but I just want to make sure.

thx a lot， and  i think padding is better  to align code, The user can enter a determined number to confirm the length of the hex dec and bin. like 10-->0x000A, means that 4 digits, and 10-->0x0000000A means 8 digits.

**Comment by attilathedud** [comment]
Released version 1.0.2 with this feature. Let me know if you have any issues.

**Comment by heartacker** [comment]
hi I have update to 1.0.2, and thx for your job. 
now we can see an option in settings named “Pad To Length”,but Most of the time we convert data, The pad-number depends on the context. not a fixed number. so that I thinks it would be better to determind the pad-number when we are converting,Popuping a  window and inputing the pad-number may be more suitable for the scene and context. :D

**Comment by attilathedud** [comment]
Alright, I think I understand. Just to clarify, you basically want the ability to alter the padding on each text conversion you do?

**Comment by heartacker** [comment]
> Alright, I think I understand. Just to clarify, you basically want the ability to alter the padding on each text conversion you do?

yes,  thanks a lot 👍

**Comment by attilathedud** [comment]
I added a variable padding option in 1.0.3. When enabled, the extension will prompt the user to provide a padding value each time they convert a selection.
